name: mountain
channels:
  - plotly
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.9.0
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2020.7.22
  - cachetools=4.1.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.5.0
  - colorama=0.4.3
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.2
  - future=0.18.2
  - gast=0.2.2
  - git=2.23.0
  - gitdb=4.0.5
  - gitpython=3.1.3
  - google-auth=1.17.2
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.4
  - hmmlearn=0.2.3
  - hyperopt=0.2.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipykernel=5.3.2
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab-git=0.20.0
  - jupyterlab_server=1.2.0
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libsodium=1.0.18
  - llvmlite=0.33.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mathjax=3.0.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbdime=2.0.0
  - nbformat=5.0.7
  - networkx=2.4
  - nodejs=10.13.0
  - notebook=6.0.3
  - numba=0.50.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - plotly=4.9.0
  - powershell_shortcut=0.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - protobuf=3.12.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pymongo=3.9.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python-kaleido=0.0.3
  - python_abi=3.7
  - pyts=0.11.0
  - pytz=2020.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - rsa=4.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=49.2.0
  - sip=4.19.8
  - six=1.15.0
  - smmap=3.0.2
  - sqlite=3.32.3
  - tbb=2020.0
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - tslearn=0.4.1
  - urllib3=1.25.9
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xlrd=1.2.0
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - hpsklearn==0.1.0
    - nose==1.3.7
